server:
  port: 9090
spring:
  application:
    name: pppig-mgtt
  #数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/p2p?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
#mybatis映射文件配置
mybatis:
  configuration:
    map-underscore-to-camel-case: false #开启驼峰命名转换
